---
test:
  name: Ecommerce Platform Test
  description: Test for the Ecommerce Platform smart contract
  workers:
    type: local
  rounds:
    - label: uploadProposal
      description: Upload a transaction proposal
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload.js
        arguments:
          action: uploadProposal
    - label: signProposal
      description: Sign the transaction proposal by merchant and platform
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload.js
        arguments:
          action: signProposal
    - label: confirmDelivery
      description: Confirm delivery
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload.js
        arguments:
          action: confirmDelivery
    - label: completeProcess
      description: Complete the process
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload.js
        arguments:
          action: completeProcess

monitor:
  type: none

ethereum:
  url: 'ws://localhost:8545'
  contract:
    address: '0x0c0f559f9fa019d7f8eb8a1274a7db193dda50f7'
    abi: [
      {
        "inputs": [
          {
            "internalType": "uint256",
            "name": "_proposalId",
            "type": "uint256"
          }
        ],
        "name": "completeProcess",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "uint256",
            "name": "_proposalId",
            "type": "uint256"
          }
        ],
        "name": "confirmDelivery",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "uint256",
            "name": "_proposalId",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "_signature",
            "type": "string"
          }
        ],
        "name": "signProposalByMerchant",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "uint256",
            "name": "_proposalId",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "_signature",
            "type": "string"
          }
        ],
        "name": "signProposalByPlatform",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "uint256",
            "name": "_productId",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "_merchantWallet",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "_price",
            "type": "uint256"
          }
        ],
        "name": "uploadTransactionProposal",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "inputs": [],
        "name": "proposalCounter",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
          }
        ],
        "name": "proposals",
        "outputs": [
          {
            "internalType": "uint256",
            "name": "productId",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "merchantWallet",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "price",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "merchantSigned",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "merchantSignature",
            "type": "string"
          },
          {
            "internalType": "bool",
            "name": "platformSigned",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "platformSignature",
            "type": "string"
          },
          {
            "internalType": "bool",
            "name": "deliveryConfirmed",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "processCompleted",
            "type": "bool"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      }
    ]
